/**********************************************************************************
*  File generated by Segger's emUSBD Audio Device Generator tool Version 1.01
*
*  Generated: 2024-06-12 12:19:20
 *  from file: Microphone_configs_16kHz.uad
*
**********************************************************************************/

// This configuration models an USB audio 1.0 device containing a speaker and a microphone,
// each connected to an USB endpoint:
//
//   +-------------+       +---------------+       +-------------------+
//   |             |       | Feature Unit  |       |                   |
//   |   Speaker   +<------+               +<------+  USB OUT endpoint |
//   |             |       | Mute / Volume |       |                   |
//   +-------------+       +---------------+       +-------------------+
//
//   +-------------+       +---------------+       +-------------------+
//   |             |       | Feature Unit  |       |                   |
//   | Microphone  +------>+               +------>+  USB IN endpoint  |
//   |             |       | Mute / Volume |       |                   |
//   +-------------+       +---------------+       +-------------------+
//
// The microphone has a single 16-bit channel (stereo) with a sample frequencies 16000Hz.


#include "USB_AC.h"


#if USBD_AC_GENERATOR_FORMAT != 1
  #error "Incompatibe data structures"
#endif


//
// Class-Specific AC Interface Descriptor
//
static const U8 _ControlDesc[] = {
  // Class-Specific AC Interface Header Descriptor
  0x09,                      // bLength
  0x24,                      // bDescriptorType
  0x01,                      // bDescriptorSubtype
  0x00, 0x01,                // bcdADC
  0x27, 0x00,                // wTotalLength
  0x01,                      // bInCollection
  0x00,                      // baInterfaceNr
  // Input Terminal Descriptor
  0x0c,                      // bLength
  0x24,                      // bDescriptorType
  0x02,                      // bDescriptorSubtype
  0x01,                      // bTerminalID
  0x01, 0x02,                // wTerminalType
  0x00,                      // bAssocTerminal
  0x02,                      // bNrChannels
  0x03, 0x00,                // bmChannelConfig
  0x00,                      // iChannelNames
  0x10,                      // iTerminal
  // Feature Unit Descriptor
  0x09,                      // bLength
  0x24,                      // bDescriptorType
  0x06,                      // bDescriptorSubtype
  0x02,                      // bUnitID
  0x01,                      // bSourceID
  0x01,                      // bControlSize
  0x03,                      // bmaControls
  0x00, 
  0x00,                      // iFeature
  // Output Terminal Descriptor
  0x09,                      // bLength
  0x24,                      // bDescriptorType
  0x03,                      // bDescriptorSubtype
  0x03,                      // bTerminalID
  0x01, 0x01,                // wTerminalType
  0x00,                      // bAssocTerminal
  0x02,                      // bSourceID
  0x00                       // iTerminal
};

//
// Class-Specific AS Interface Descriptor
//
static const U8 _StreamDesc_0_1[] = {
  // Class-Specific AS Interface Header Descriptor
  0x07,                      // bLength
  0x24,                      // bDescriptorType
  0x01,                      // bDescriptorSubtype
  0x03,                      // bTerminalLink
  0x00,                      // bDelay
  0x01, 0x00,                // wFormatTag
  // Type I Format Type Descriptor
  0x0b,                      // bLength
  0x24,                      // bDescriptorType
  0x02,                      // bDescriptorSubtype
  0x01,                      // bFormatType
  0x02,                      // bNrChannels
  0x02,                      // bSubframeSize
  0x10,                      // bBitResolution
  0x01,                      // bSamFreqType
  0x80, 0x3e, 0x00           // tSamFreq
};

//
// Class-Specific AS Isochronous Audio Data Endpoint Descriptor
//
static const U8 _StreamEPDesc_0_1[] = {
  0x07,                      // bLength
  0x25,                      // bDescriptorType
  0x01,                      // bDescriptorSubtype
  0x01,                      // bmAttributes
  0x00,                      // bLockDelayUnits
  0x00, 0x00                 // wLockDelay
};

//
// String table
//
static const char * const _Strings[] = {
  "Microphone",
  "Audio Microphone"
};

//
// Endpoint table
//
static const USBD_AC_EP_INFO _Endpoints[] = {
  {  1, 0, {    64,    8, USB_ADD_EP_FLAG_USE_ISO_SYNC_TYPES, USB_DIR_IN,  USB_TRANSFER_TYPE_ISO,  USB_ISO_SYNC_TYPE_SYNCHRONOUS }}
};

//
// Interface info for interface 'Microphone'
//
static const USBD_AC_INTF_INFO _Interface_0[] = {
  {            // Alt setting 0
      17,      // String index
      -1,      // Data EP index
      -1,      // Feedback EP index
    0,
    NULL,
    NULL,
    0,
    {
       0,      // MaxPacketSize
       0,      // IntervalExp
       0,      // NrChannels
       0,      // SubframeSize
       0       // BitResolution
    }
  },
  {            // Alt setting 1
      17,      // String index
       0,      // Data EP index
      -1,      // Feedback EP index
    sizeof(_StreamEPDesc_0_1),
    _StreamEPDesc_0_1,
    _StreamDesc_0_1,
    sizeof(_StreamDesc_0_1),
    {
      64,      // MaxPacketSize
        3,      // IntervalExp
        2,      // NrChannels
        2,      // SubframeSize
      16       // BitResolution
    }
  }
};

//
// Interface list
//
static const USBD_AC_INTF_LIST _InterfaceList[] = {
  { 2, 1, _Interface_0 }
};

//
// Configuration for 'Microphone_configs'
//
extern const USBD_AC_CONFIG USB_AC_Config_Microphone_configs;

const USBD_AC_CONFIG USB_AC_Config_Microphone_configs = {
   1,        // Generator major version
   0,        // USB audio protocol version
   1,        // Number of streaming interfaces
   1,        // Number of endpoints
  16,        // Index of first string in string table
   2,        // Number of strings in string table
   0,        // String index for control interface.
  sizeof(_ControlDesc),
  _ControlDesc,              // Control interface descriptor
  _InterfaceList,            // Streaming interfaces
  _Endpoints,                // Endpoint list
  _Strings                   // String descriptors
};

